// src/api/services/index.js
export { authService } from './auth.service'
export { programsService } from './programs.service'
export { studentsService } from './students.service'
export { teachersService } from './teachers.service'
export { guardiansService } from './guardians.service'
export { registrationsService } from './registrations.service'
export { subjectsService } from './subjects.service'
export { timetableService } from './timetable.service'
export { schoolClassService } from './schoolClass.service'